export const addCustomerTab = '[ng-class="btnClass1"]'
export const fnameField = '[ng-model="fName"]'
export const lnameField = '[ng-model="lName"]'
export const postCodeField = '[ng-model="postCd"]'
export const addCustomerBtn = '[class="btn btn-default"]'
export const addCustSucMsg = '[Customer added successfully]'
